# Output git tag or version hash to config.h.
# Use the name config.h since cmdline.c generated by gengetopt includes it automatically.
config.h: SHELL := /bin/bash
config.h: Makefile ../.git
	VERSION_STR=`../tools/git_version.sh`; \
	printf "#define CMDLINE_PARSER_VERSION \"%s\"\n" "$${VERSION_STR}" > config.h
