package:
  name: vcf2multialign
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

source:
  path: ..

requirements:
  build:
    - boost-cpp =1.82.0
    - clang >=16.0.6
    - clangxx >=16.0.6
#    - libcxx >=16.0.6
#    - libstdcxx-ng >=12.3.0
#    - libstdcxx-devel_linux-64 >=12.3.0
    - sysroot_linux-64 >=2.28
  run:
    - boost-cpp =1.82.#0
#    - libstdcxx-ng >=12.3.0
#    - libgcc-ng >=12.3.0
    - zlib >=1.2.13

about:
  home: https://github.com/tsnorri/vcf2multialign
  license: MIT
  description: "Create a set of reference-guided multiple-aligned predicted or founder sequences from a variant call file and a reference sequence."
