package:
  name: vcf2multialign
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

source:
  path: ..

requirements:
  build:
    - boost-cpp=1.74.0
    - clang>=17.0.6
    - clangxx>=17.0.6
    - gengetopt>=2.23
    - libgcc-ng>=13.2.0
    - libstdcxx-ng>=13.2.0
    - libstdcxx-devel_linux-64>=13.2.0
    - libzlib>=1.2.13
    - ragel >=6.10
    - sysroot_linux-64>=2.28
  run:
    - boost-cpp=1.74.0
    - libgcc-ng>=13.2.0
    - libstdcxx-ng>=13.2.0
    - libzlib>=1.2.13
    - sysroot_linux-64>=2.28

about:
  home: https://github.com/tsnorri/vcf2multialign
  license: MIT
  description: "Create a set of reference-guided multiple-aligned predicted or founder sequences from a variant call file and a reference sequence."
