package:
  name: vcf2multialign
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

source:
  path: ..

requirements:
  build:
    - boost-cpp=1.74.0
    - clang>=9.0.0
    - clangxx>=9.0.0
#    - libcxx>=9.0.0
    - libstdcxx-ng>=9.3.0
    - libstdcxx-devel_linux-64>=9.3.0
    - sysroot_linux-64>=2.17
  run:
    - zlib>=1.2.11
    - libstdcxx-ng>=9.3.0
    - boost-cpp>=1.74.0
    - libgcc-ng>=9.3.0

about:
  home: https://github.com/tsnorri/vcf2multialign
  licence: MIT
  summary: "Create a set of reference-guided multiple-aligned predicted or founder sequences from a variant call file and a reference sequence."
