package:
  name: vcf2multialign
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

source:
  path: ..

requirements:
  build:
    - gcc >=12.3.0
    - gengetopt >=2.23
    - gxx >=12.3.0,<13
    - libboost =1.82.0
    - libboost-headers =1.82.0
    - libstdcxx-devel_linux-64 >=12.3.0,<13
    - libstdcxx-ng >=12.3.0,<13
    - libzlib >=1.3.1
    - ragel >=6.10
    - sysroot_linux-64 >=2.28
    - zlib >=1.3.1
  run:
    - libboost =1.82.0
    - libgcc-ng >=12.3.0
    - libstdcxx-ng >=12.3.0
    - libzlib >=1.3.1

about:
  home: https://github.com/tsnorri/vcf2multialign
  license: MIT
  description: "Create a set of reference-guided multiple-aligned predicted or founder sequences from a variant call file and a reference sequence."
